// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package http

//go:generate minimock -i github.com/etilite/firebase-messenger/internal/delivery/http.pusher -o zzz_pusher_mock_test.go -n PusherMock -p http

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/etilite/firebase-messenger/internal/model"
	"github.com/gojuno/minimock/v3"
)

// PusherMock implements pusher
type PusherMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcPush          func(ctx context.Context, request model.SendRequest) (s1 model.SendResponse, err error)
	funcPushOrigin    string
	inspectFuncPush   func(ctx context.Context, request model.SendRequest)
	afterPushCounter  uint64
	beforePushCounter uint64
	PushMock          mPusherMockPush
}

// NewPusherMock returns a mock for pusher
func NewPusherMock(t minimock.Tester) *PusherMock {
	m := &PusherMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.PushMock = mPusherMockPush{mock: m}
	m.PushMock.callArgs = []*PusherMockPushParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mPusherMockPush struct {
	optional           bool
	mock               *PusherMock
	defaultExpectation *PusherMockPushExpectation
	expectations       []*PusherMockPushExpectation

	callArgs []*PusherMockPushParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// PusherMockPushExpectation specifies expectation struct of the pusher.Push
type PusherMockPushExpectation struct {
	mock               *PusherMock
	params             *PusherMockPushParams
	paramPtrs          *PusherMockPushParamPtrs
	expectationOrigins PusherMockPushExpectationOrigins
	results            *PusherMockPushResults
	returnOrigin       string
	Counter            uint64
}

// PusherMockPushParams contains parameters of the pusher.Push
type PusherMockPushParams struct {
	ctx     context.Context
	request model.SendRequest
}

// PusherMockPushParamPtrs contains pointers to parameters of the pusher.Push
type PusherMockPushParamPtrs struct {
	ctx     *context.Context
	request *model.SendRequest
}

// PusherMockPushResults contains results of the pusher.Push
type PusherMockPushResults struct {
	s1  model.SendResponse
	err error
}

// PusherMockPushOrigins contains origins of expectations of the pusher.Push
type PusherMockPushExpectationOrigins struct {
	origin        string
	originCtx     string
	originRequest string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmPush *mPusherMockPush) Optional() *mPusherMockPush {
	mmPush.optional = true
	return mmPush
}

// Expect sets up expected params for pusher.Push
func (mmPush *mPusherMockPush) Expect(ctx context.Context, request model.SendRequest) *mPusherMockPush {
	if mmPush.mock.funcPush != nil {
		mmPush.mock.t.Fatalf("PusherMock.Push mock is already set by Set")
	}

	if mmPush.defaultExpectation == nil {
		mmPush.defaultExpectation = &PusherMockPushExpectation{}
	}

	if mmPush.defaultExpectation.paramPtrs != nil {
		mmPush.mock.t.Fatalf("PusherMock.Push mock is already set by ExpectParams functions")
	}

	mmPush.defaultExpectation.params = &PusherMockPushParams{ctx, request}
	mmPush.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmPush.expectations {
		if minimock.Equal(e.params, mmPush.defaultExpectation.params) {
			mmPush.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmPush.defaultExpectation.params)
		}
	}

	return mmPush
}

// ExpectCtxParam1 sets up expected param ctx for pusher.Push
func (mmPush *mPusherMockPush) ExpectCtxParam1(ctx context.Context) *mPusherMockPush {
	if mmPush.mock.funcPush != nil {
		mmPush.mock.t.Fatalf("PusherMock.Push mock is already set by Set")
	}

	if mmPush.defaultExpectation == nil {
		mmPush.defaultExpectation = &PusherMockPushExpectation{}
	}

	if mmPush.defaultExpectation.params != nil {
		mmPush.mock.t.Fatalf("PusherMock.Push mock is already set by Expect")
	}

	if mmPush.defaultExpectation.paramPtrs == nil {
		mmPush.defaultExpectation.paramPtrs = &PusherMockPushParamPtrs{}
	}
	mmPush.defaultExpectation.paramPtrs.ctx = &ctx
	mmPush.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmPush
}

// ExpectRequestParam2 sets up expected param request for pusher.Push
func (mmPush *mPusherMockPush) ExpectRequestParam2(request model.SendRequest) *mPusherMockPush {
	if mmPush.mock.funcPush != nil {
		mmPush.mock.t.Fatalf("PusherMock.Push mock is already set by Set")
	}

	if mmPush.defaultExpectation == nil {
		mmPush.defaultExpectation = &PusherMockPushExpectation{}
	}

	if mmPush.defaultExpectation.params != nil {
		mmPush.mock.t.Fatalf("PusherMock.Push mock is already set by Expect")
	}

	if mmPush.defaultExpectation.paramPtrs == nil {
		mmPush.defaultExpectation.paramPtrs = &PusherMockPushParamPtrs{}
	}
	mmPush.defaultExpectation.paramPtrs.request = &request
	mmPush.defaultExpectation.expectationOrigins.originRequest = minimock.CallerInfo(1)

	return mmPush
}

// Inspect accepts an inspector function that has same arguments as the pusher.Push
func (mmPush *mPusherMockPush) Inspect(f func(ctx context.Context, request model.SendRequest)) *mPusherMockPush {
	if mmPush.mock.inspectFuncPush != nil {
		mmPush.mock.t.Fatalf("Inspect function is already set for PusherMock.Push")
	}

	mmPush.mock.inspectFuncPush = f

	return mmPush
}

// Return sets up results that will be returned by pusher.Push
func (mmPush *mPusherMockPush) Return(s1 model.SendResponse, err error) *PusherMock {
	if mmPush.mock.funcPush != nil {
		mmPush.mock.t.Fatalf("PusherMock.Push mock is already set by Set")
	}

	if mmPush.defaultExpectation == nil {
		mmPush.defaultExpectation = &PusherMockPushExpectation{mock: mmPush.mock}
	}
	mmPush.defaultExpectation.results = &PusherMockPushResults{s1, err}
	mmPush.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmPush.mock
}

// Set uses given function f to mock the pusher.Push method
func (mmPush *mPusherMockPush) Set(f func(ctx context.Context, request model.SendRequest) (s1 model.SendResponse, err error)) *PusherMock {
	if mmPush.defaultExpectation != nil {
		mmPush.mock.t.Fatalf("Default expectation is already set for the pusher.Push method")
	}

	if len(mmPush.expectations) > 0 {
		mmPush.mock.t.Fatalf("Some expectations are already set for the pusher.Push method")
	}

	mmPush.mock.funcPush = f
	mmPush.mock.funcPushOrigin = minimock.CallerInfo(1)
	return mmPush.mock
}

// When sets expectation for the pusher.Push which will trigger the result defined by the following
// Then helper
func (mmPush *mPusherMockPush) When(ctx context.Context, request model.SendRequest) *PusherMockPushExpectation {
	if mmPush.mock.funcPush != nil {
		mmPush.mock.t.Fatalf("PusherMock.Push mock is already set by Set")
	}

	expectation := &PusherMockPushExpectation{
		mock:               mmPush.mock,
		params:             &PusherMockPushParams{ctx, request},
		expectationOrigins: PusherMockPushExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmPush.expectations = append(mmPush.expectations, expectation)
	return expectation
}

// Then sets up pusher.Push return parameters for the expectation previously defined by the When method
func (e *PusherMockPushExpectation) Then(s1 model.SendResponse, err error) *PusherMock {
	e.results = &PusherMockPushResults{s1, err}
	return e.mock
}

// Times sets number of times pusher.Push should be invoked
func (mmPush *mPusherMockPush) Times(n uint64) *mPusherMockPush {
	if n == 0 {
		mmPush.mock.t.Fatalf("Times of PusherMock.Push mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmPush.expectedInvocations, n)
	mmPush.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmPush
}

func (mmPush *mPusherMockPush) invocationsDone() bool {
	if len(mmPush.expectations) == 0 && mmPush.defaultExpectation == nil && mmPush.mock.funcPush == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmPush.mock.afterPushCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmPush.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Push implements pusher
func (mmPush *PusherMock) Push(ctx context.Context, request model.SendRequest) (s1 model.SendResponse, err error) {
	mm_atomic.AddUint64(&mmPush.beforePushCounter, 1)
	defer mm_atomic.AddUint64(&mmPush.afterPushCounter, 1)

	mmPush.t.Helper()

	if mmPush.inspectFuncPush != nil {
		mmPush.inspectFuncPush(ctx, request)
	}

	mm_params := PusherMockPushParams{ctx, request}

	// Record call args
	mmPush.PushMock.mutex.Lock()
	mmPush.PushMock.callArgs = append(mmPush.PushMock.callArgs, &mm_params)
	mmPush.PushMock.mutex.Unlock()

	for _, e := range mmPush.PushMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmPush.PushMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmPush.PushMock.defaultExpectation.Counter, 1)
		mm_want := mmPush.PushMock.defaultExpectation.params
		mm_want_ptrs := mmPush.PushMock.defaultExpectation.paramPtrs

		mm_got := PusherMockPushParams{ctx, request}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmPush.t.Errorf("PusherMock.Push got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmPush.PushMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.request != nil && !minimock.Equal(*mm_want_ptrs.request, mm_got.request) {
				mmPush.t.Errorf("PusherMock.Push got unexpected parameter request, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmPush.PushMock.defaultExpectation.expectationOrigins.originRequest, *mm_want_ptrs.request, mm_got.request, minimock.Diff(*mm_want_ptrs.request, mm_got.request))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmPush.t.Errorf("PusherMock.Push got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmPush.PushMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmPush.PushMock.defaultExpectation.results
		if mm_results == nil {
			mmPush.t.Fatal("No results are set for the PusherMock.Push")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmPush.funcPush != nil {
		return mmPush.funcPush(ctx, request)
	}
	mmPush.t.Fatalf("Unexpected call to PusherMock.Push. %v %v", ctx, request)
	return
}

// PushAfterCounter returns a count of finished PusherMock.Push invocations
func (mmPush *PusherMock) PushAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPush.afterPushCounter)
}

// PushBeforeCounter returns a count of PusherMock.Push invocations
func (mmPush *PusherMock) PushBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPush.beforePushCounter)
}

// Calls returns a list of arguments used in each call to PusherMock.Push.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmPush *mPusherMockPush) Calls() []*PusherMockPushParams {
	mmPush.mutex.RLock()

	argCopy := make([]*PusherMockPushParams, len(mmPush.callArgs))
	copy(argCopy, mmPush.callArgs)

	mmPush.mutex.RUnlock()

	return argCopy
}

// MinimockPushDone returns true if the count of the Push invocations corresponds
// the number of defined expectations
func (m *PusherMock) MinimockPushDone() bool {
	if m.PushMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.PushMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.PushMock.invocationsDone()
}

// MinimockPushInspect logs each unmet expectation
func (m *PusherMock) MinimockPushInspect() {
	for _, e := range m.PushMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to PusherMock.Push at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterPushCounter := mm_atomic.LoadUint64(&m.afterPushCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.PushMock.defaultExpectation != nil && afterPushCounter < 1 {
		if m.PushMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to PusherMock.Push at\n%s", m.PushMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to PusherMock.Push at\n%s with params: %#v", m.PushMock.defaultExpectation.expectationOrigins.origin, *m.PushMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcPush != nil && afterPushCounter < 1 {
		m.t.Errorf("Expected call to PusherMock.Push at\n%s", m.funcPushOrigin)
	}

	if !m.PushMock.invocationsDone() && afterPushCounter > 0 {
		m.t.Errorf("Expected %d calls to PusherMock.Push at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.PushMock.expectedInvocations), m.PushMock.expectedInvocationsOrigin, afterPushCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *PusherMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockPushInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *PusherMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *PusherMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockPushDone()
}
