// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package firebase

//go:generate minimock -i github.com/etilite/firebase-messenger/internal/firebase.client -o zzz_client_mock_test.go -n ClientMock -p firebase

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"firebase.google.com/go/v4/messaging"
	"github.com/gojuno/minimock/v3"
)

// ClientMock implements client
type ClientMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcSendEachForMulticast          func(ctx context.Context, message *messaging.MulticastMessage) (bp1 *messaging.BatchResponse, err error)
	funcSendEachForMulticastOrigin    string
	inspectFuncSendEachForMulticast   func(ctx context.Context, message *messaging.MulticastMessage)
	afterSendEachForMulticastCounter  uint64
	beforeSendEachForMulticastCounter uint64
	SendEachForMulticastMock          mClientMockSendEachForMulticast
}

// NewClientMock returns a mock for client
func NewClientMock(t minimock.Tester) *ClientMock {
	m := &ClientMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.SendEachForMulticastMock = mClientMockSendEachForMulticast{mock: m}
	m.SendEachForMulticastMock.callArgs = []*ClientMockSendEachForMulticastParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mClientMockSendEachForMulticast struct {
	optional           bool
	mock               *ClientMock
	defaultExpectation *ClientMockSendEachForMulticastExpectation
	expectations       []*ClientMockSendEachForMulticastExpectation

	callArgs []*ClientMockSendEachForMulticastParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ClientMockSendEachForMulticastExpectation specifies expectation struct of the client.SendEachForMulticast
type ClientMockSendEachForMulticastExpectation struct {
	mock               *ClientMock
	params             *ClientMockSendEachForMulticastParams
	paramPtrs          *ClientMockSendEachForMulticastParamPtrs
	expectationOrigins ClientMockSendEachForMulticastExpectationOrigins
	results            *ClientMockSendEachForMulticastResults
	returnOrigin       string
	Counter            uint64
}

// ClientMockSendEachForMulticastParams contains parameters of the client.SendEachForMulticast
type ClientMockSendEachForMulticastParams struct {
	ctx     context.Context
	message *messaging.MulticastMessage
}

// ClientMockSendEachForMulticastParamPtrs contains pointers to parameters of the client.SendEachForMulticast
type ClientMockSendEachForMulticastParamPtrs struct {
	ctx     *context.Context
	message **messaging.MulticastMessage
}

// ClientMockSendEachForMulticastResults contains results of the client.SendEachForMulticast
type ClientMockSendEachForMulticastResults struct {
	bp1 *messaging.BatchResponse
	err error
}

// ClientMockSendEachForMulticastOrigins contains origins of expectations of the client.SendEachForMulticast
type ClientMockSendEachForMulticastExpectationOrigins struct {
	origin        string
	originCtx     string
	originMessage string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSendEachForMulticast *mClientMockSendEachForMulticast) Optional() *mClientMockSendEachForMulticast {
	mmSendEachForMulticast.optional = true
	return mmSendEachForMulticast
}

// Expect sets up expected params for client.SendEachForMulticast
func (mmSendEachForMulticast *mClientMockSendEachForMulticast) Expect(ctx context.Context, message *messaging.MulticastMessage) *mClientMockSendEachForMulticast {
	if mmSendEachForMulticast.mock.funcSendEachForMulticast != nil {
		mmSendEachForMulticast.mock.t.Fatalf("ClientMock.SendEachForMulticast mock is already set by Set")
	}

	if mmSendEachForMulticast.defaultExpectation == nil {
		mmSendEachForMulticast.defaultExpectation = &ClientMockSendEachForMulticastExpectation{}
	}

	if mmSendEachForMulticast.defaultExpectation.paramPtrs != nil {
		mmSendEachForMulticast.mock.t.Fatalf("ClientMock.SendEachForMulticast mock is already set by ExpectParams functions")
	}

	mmSendEachForMulticast.defaultExpectation.params = &ClientMockSendEachForMulticastParams{ctx, message}
	mmSendEachForMulticast.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSendEachForMulticast.expectations {
		if minimock.Equal(e.params, mmSendEachForMulticast.defaultExpectation.params) {
			mmSendEachForMulticast.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSendEachForMulticast.defaultExpectation.params)
		}
	}

	return mmSendEachForMulticast
}

// ExpectCtxParam1 sets up expected param ctx for client.SendEachForMulticast
func (mmSendEachForMulticast *mClientMockSendEachForMulticast) ExpectCtxParam1(ctx context.Context) *mClientMockSendEachForMulticast {
	if mmSendEachForMulticast.mock.funcSendEachForMulticast != nil {
		mmSendEachForMulticast.mock.t.Fatalf("ClientMock.SendEachForMulticast mock is already set by Set")
	}

	if mmSendEachForMulticast.defaultExpectation == nil {
		mmSendEachForMulticast.defaultExpectation = &ClientMockSendEachForMulticastExpectation{}
	}

	if mmSendEachForMulticast.defaultExpectation.params != nil {
		mmSendEachForMulticast.mock.t.Fatalf("ClientMock.SendEachForMulticast mock is already set by Expect")
	}

	if mmSendEachForMulticast.defaultExpectation.paramPtrs == nil {
		mmSendEachForMulticast.defaultExpectation.paramPtrs = &ClientMockSendEachForMulticastParamPtrs{}
	}
	mmSendEachForMulticast.defaultExpectation.paramPtrs.ctx = &ctx
	mmSendEachForMulticast.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSendEachForMulticast
}

// ExpectMessageParam2 sets up expected param message for client.SendEachForMulticast
func (mmSendEachForMulticast *mClientMockSendEachForMulticast) ExpectMessageParam2(message *messaging.MulticastMessage) *mClientMockSendEachForMulticast {
	if mmSendEachForMulticast.mock.funcSendEachForMulticast != nil {
		mmSendEachForMulticast.mock.t.Fatalf("ClientMock.SendEachForMulticast mock is already set by Set")
	}

	if mmSendEachForMulticast.defaultExpectation == nil {
		mmSendEachForMulticast.defaultExpectation = &ClientMockSendEachForMulticastExpectation{}
	}

	if mmSendEachForMulticast.defaultExpectation.params != nil {
		mmSendEachForMulticast.mock.t.Fatalf("ClientMock.SendEachForMulticast mock is already set by Expect")
	}

	if mmSendEachForMulticast.defaultExpectation.paramPtrs == nil {
		mmSendEachForMulticast.defaultExpectation.paramPtrs = &ClientMockSendEachForMulticastParamPtrs{}
	}
	mmSendEachForMulticast.defaultExpectation.paramPtrs.message = &message
	mmSendEachForMulticast.defaultExpectation.expectationOrigins.originMessage = minimock.CallerInfo(1)

	return mmSendEachForMulticast
}

// Inspect accepts an inspector function that has same arguments as the client.SendEachForMulticast
func (mmSendEachForMulticast *mClientMockSendEachForMulticast) Inspect(f func(ctx context.Context, message *messaging.MulticastMessage)) *mClientMockSendEachForMulticast {
	if mmSendEachForMulticast.mock.inspectFuncSendEachForMulticast != nil {
		mmSendEachForMulticast.mock.t.Fatalf("Inspect function is already set for ClientMock.SendEachForMulticast")
	}

	mmSendEachForMulticast.mock.inspectFuncSendEachForMulticast = f

	return mmSendEachForMulticast
}

// Return sets up results that will be returned by client.SendEachForMulticast
func (mmSendEachForMulticast *mClientMockSendEachForMulticast) Return(bp1 *messaging.BatchResponse, err error) *ClientMock {
	if mmSendEachForMulticast.mock.funcSendEachForMulticast != nil {
		mmSendEachForMulticast.mock.t.Fatalf("ClientMock.SendEachForMulticast mock is already set by Set")
	}

	if mmSendEachForMulticast.defaultExpectation == nil {
		mmSendEachForMulticast.defaultExpectation = &ClientMockSendEachForMulticastExpectation{mock: mmSendEachForMulticast.mock}
	}
	mmSendEachForMulticast.defaultExpectation.results = &ClientMockSendEachForMulticastResults{bp1, err}
	mmSendEachForMulticast.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSendEachForMulticast.mock
}

// Set uses given function f to mock the client.SendEachForMulticast method
func (mmSendEachForMulticast *mClientMockSendEachForMulticast) Set(f func(ctx context.Context, message *messaging.MulticastMessage) (bp1 *messaging.BatchResponse, err error)) *ClientMock {
	if mmSendEachForMulticast.defaultExpectation != nil {
		mmSendEachForMulticast.mock.t.Fatalf("Default expectation is already set for the client.SendEachForMulticast method")
	}

	if len(mmSendEachForMulticast.expectations) > 0 {
		mmSendEachForMulticast.mock.t.Fatalf("Some expectations are already set for the client.SendEachForMulticast method")
	}

	mmSendEachForMulticast.mock.funcSendEachForMulticast = f
	mmSendEachForMulticast.mock.funcSendEachForMulticastOrigin = minimock.CallerInfo(1)
	return mmSendEachForMulticast.mock
}

// When sets expectation for the client.SendEachForMulticast which will trigger the result defined by the following
// Then helper
func (mmSendEachForMulticast *mClientMockSendEachForMulticast) When(ctx context.Context, message *messaging.MulticastMessage) *ClientMockSendEachForMulticastExpectation {
	if mmSendEachForMulticast.mock.funcSendEachForMulticast != nil {
		mmSendEachForMulticast.mock.t.Fatalf("ClientMock.SendEachForMulticast mock is already set by Set")
	}

	expectation := &ClientMockSendEachForMulticastExpectation{
		mock:               mmSendEachForMulticast.mock,
		params:             &ClientMockSendEachForMulticastParams{ctx, message},
		expectationOrigins: ClientMockSendEachForMulticastExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSendEachForMulticast.expectations = append(mmSendEachForMulticast.expectations, expectation)
	return expectation
}

// Then sets up client.SendEachForMulticast return parameters for the expectation previously defined by the When method
func (e *ClientMockSendEachForMulticastExpectation) Then(bp1 *messaging.BatchResponse, err error) *ClientMock {
	e.results = &ClientMockSendEachForMulticastResults{bp1, err}
	return e.mock
}

// Times sets number of times client.SendEachForMulticast should be invoked
func (mmSendEachForMulticast *mClientMockSendEachForMulticast) Times(n uint64) *mClientMockSendEachForMulticast {
	if n == 0 {
		mmSendEachForMulticast.mock.t.Fatalf("Times of ClientMock.SendEachForMulticast mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSendEachForMulticast.expectedInvocations, n)
	mmSendEachForMulticast.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSendEachForMulticast
}

func (mmSendEachForMulticast *mClientMockSendEachForMulticast) invocationsDone() bool {
	if len(mmSendEachForMulticast.expectations) == 0 && mmSendEachForMulticast.defaultExpectation == nil && mmSendEachForMulticast.mock.funcSendEachForMulticast == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSendEachForMulticast.mock.afterSendEachForMulticastCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSendEachForMulticast.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SendEachForMulticast implements client
func (mmSendEachForMulticast *ClientMock) SendEachForMulticast(ctx context.Context, message *messaging.MulticastMessage) (bp1 *messaging.BatchResponse, err error) {
	mm_atomic.AddUint64(&mmSendEachForMulticast.beforeSendEachForMulticastCounter, 1)
	defer mm_atomic.AddUint64(&mmSendEachForMulticast.afterSendEachForMulticastCounter, 1)

	mmSendEachForMulticast.t.Helper()

	if mmSendEachForMulticast.inspectFuncSendEachForMulticast != nil {
		mmSendEachForMulticast.inspectFuncSendEachForMulticast(ctx, message)
	}

	mm_params := ClientMockSendEachForMulticastParams{ctx, message}

	// Record call args
	mmSendEachForMulticast.SendEachForMulticastMock.mutex.Lock()
	mmSendEachForMulticast.SendEachForMulticastMock.callArgs = append(mmSendEachForMulticast.SendEachForMulticastMock.callArgs, &mm_params)
	mmSendEachForMulticast.SendEachForMulticastMock.mutex.Unlock()

	for _, e := range mmSendEachForMulticast.SendEachForMulticastMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.bp1, e.results.err
		}
	}

	if mmSendEachForMulticast.SendEachForMulticastMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSendEachForMulticast.SendEachForMulticastMock.defaultExpectation.Counter, 1)
		mm_want := mmSendEachForMulticast.SendEachForMulticastMock.defaultExpectation.params
		mm_want_ptrs := mmSendEachForMulticast.SendEachForMulticastMock.defaultExpectation.paramPtrs

		mm_got := ClientMockSendEachForMulticastParams{ctx, message}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSendEachForMulticast.t.Errorf("ClientMock.SendEachForMulticast got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSendEachForMulticast.SendEachForMulticastMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.message != nil && !minimock.Equal(*mm_want_ptrs.message, mm_got.message) {
				mmSendEachForMulticast.t.Errorf("ClientMock.SendEachForMulticast got unexpected parameter message, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSendEachForMulticast.SendEachForMulticastMock.defaultExpectation.expectationOrigins.originMessage, *mm_want_ptrs.message, mm_got.message, minimock.Diff(*mm_want_ptrs.message, mm_got.message))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSendEachForMulticast.t.Errorf("ClientMock.SendEachForMulticast got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSendEachForMulticast.SendEachForMulticastMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSendEachForMulticast.SendEachForMulticastMock.defaultExpectation.results
		if mm_results == nil {
			mmSendEachForMulticast.t.Fatal("No results are set for the ClientMock.SendEachForMulticast")
		}
		return (*mm_results).bp1, (*mm_results).err
	}
	if mmSendEachForMulticast.funcSendEachForMulticast != nil {
		return mmSendEachForMulticast.funcSendEachForMulticast(ctx, message)
	}
	mmSendEachForMulticast.t.Fatalf("Unexpected call to ClientMock.SendEachForMulticast. %v %v", ctx, message)
	return
}

// SendEachForMulticastAfterCounter returns a count of finished ClientMock.SendEachForMulticast invocations
func (mmSendEachForMulticast *ClientMock) SendEachForMulticastAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSendEachForMulticast.afterSendEachForMulticastCounter)
}

// SendEachForMulticastBeforeCounter returns a count of ClientMock.SendEachForMulticast invocations
func (mmSendEachForMulticast *ClientMock) SendEachForMulticastBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSendEachForMulticast.beforeSendEachForMulticastCounter)
}

// Calls returns a list of arguments used in each call to ClientMock.SendEachForMulticast.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSendEachForMulticast *mClientMockSendEachForMulticast) Calls() []*ClientMockSendEachForMulticastParams {
	mmSendEachForMulticast.mutex.RLock()

	argCopy := make([]*ClientMockSendEachForMulticastParams, len(mmSendEachForMulticast.callArgs))
	copy(argCopy, mmSendEachForMulticast.callArgs)

	mmSendEachForMulticast.mutex.RUnlock()

	return argCopy
}

// MinimockSendEachForMulticastDone returns true if the count of the SendEachForMulticast invocations corresponds
// the number of defined expectations
func (m *ClientMock) MinimockSendEachForMulticastDone() bool {
	if m.SendEachForMulticastMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SendEachForMulticastMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SendEachForMulticastMock.invocationsDone()
}

// MinimockSendEachForMulticastInspect logs each unmet expectation
func (m *ClientMock) MinimockSendEachForMulticastInspect() {
	for _, e := range m.SendEachForMulticastMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ClientMock.SendEachForMulticast at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSendEachForMulticastCounter := mm_atomic.LoadUint64(&m.afterSendEachForMulticastCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SendEachForMulticastMock.defaultExpectation != nil && afterSendEachForMulticastCounter < 1 {
		if m.SendEachForMulticastMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ClientMock.SendEachForMulticast at\n%s", m.SendEachForMulticastMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ClientMock.SendEachForMulticast at\n%s with params: %#v", m.SendEachForMulticastMock.defaultExpectation.expectationOrigins.origin, *m.SendEachForMulticastMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSendEachForMulticast != nil && afterSendEachForMulticastCounter < 1 {
		m.t.Errorf("Expected call to ClientMock.SendEachForMulticast at\n%s", m.funcSendEachForMulticastOrigin)
	}

	if !m.SendEachForMulticastMock.invocationsDone() && afterSendEachForMulticastCounter > 0 {
		m.t.Errorf("Expected %d calls to ClientMock.SendEachForMulticast at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SendEachForMulticastMock.expectedInvocations), m.SendEachForMulticastMock.expectedInvocationsOrigin, afterSendEachForMulticastCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ClientMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockSendEachForMulticastInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ClientMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ClientMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockSendEachForMulticastDone()
}
